name = "TinyHiGHS"
uuid = "e3bf2cee-ebdb-4187-a929-02449a8c6d58"
version = "0.1.0"

[compat]
MathOptInterface = "1.25"
julia = "1.10"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extensions]
TinyHiGHSMathOptInterfaceExt = "MathOptInterface"

[extras]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Printf", "MathOptInterface"]
